site_name: mkdocs-demo
site_author: ntno

nav:
    - Home: 'index.md'
    
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
  palette:
    primary: light-green
    accent: amber

plugins:
  - search
  - markdown-filter
  - macros

extra:
  GREETING: !ENV [GREETING]
  NAME: !ENV [NAME]
  ENV_LEVEL: !ENV [ENV_LEVEL]
  REGION: !ENV [REGION]