site_name: mkdocs-demo
copyright: Copyright 2023 ntno
site_author: ntno

nav:
    - Home: 'index.md'
    - Troubleshooting: 'help.md'
    - About: 
      - Index: 'about/index.md'
      - Contributing: 'about/contributing.md'
      - License: 'about/license.md'
      - Release Notes:
        - Index: 'about/release-notes/index.md'
        - v1: 'about/release-notes/version-1.md'
        - v2: 'about/release-notes/version-2.md'
    - User Guide:
      - Configuration: 'user-guide/configuration.md'
      - Custom Themes: 'user-guide/custom-themes.md'
      - Deployment: 'user-guide/deploying-your-docs.md'
      - Styling: 'user-guide/styling-your-docs.md'
      - Writing: 'user-guide/writing-your-docs.md'
    
markdown_extensions:
  - meta
  - attr_list
  - toc:
      permalink: "#"

theme:
  name: terminal
  features:
    # - toc.hide
    # - navigation.side.hide
    - navigation.side.indexes
    # - navigation.top.hide
    # - navigation.top.cursor_animation.hide

plugins:
  - markdown-filter
  - macros

extra:
  GREETING: !ENV [GREETING]
  NAME: !ENV [NAME]
  ENV_LEVEL: !ENV [ENV_LEVEL]
  REGION: !ENV [REGION]