site_name: mkdocs-demo
site_author: ntno

nav:
    - Home: 'index.md'
    - Troubleshooting: 'help.md'
    - About: 
      - Index: 'about/index.md'
      - Contributing: 'about/contributing.md'
      - License: 'about/license.md'
      - Release Notes:
        - Index: 'about/release-notes/index.md'
        - v1: 'about/release-notes/version-1.md'
        - v2: 'about/release-notes/version-2.md'
    - User Guide:
      - Configuration: 'user-guide/configuration.md'
      - Custom Themes: 'user-guide/custom-themes.md'
      - Deployment: 'user-guide/deploying-your-docs.md'
      - Styling: 'user-guide/styling-your-docs.md'
      - Writing: 'user-guide/writing-your-docs.md'
    - Plugins:
      - Macros: 'macros-test.md'
    
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

theme:
  name: terminal


plugins:
  - search
  - markdown-filter
  - macros

extra:
  GREETING: !ENV [GREETING]
  NAME: !ENV [NAME]
  ENV_LEVEL: !ENV [ENV_LEVEL]
  REGION: !ENV [REGION]