name: Open Pull Request

# only trigger on pull request open or reopen events
on:
  pull_request:
    types: [ opened, reopened ]

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  call-metadata-workflow:
    uses: ./.github/workflows/meta.yml 
    secrets: inherit
    with:
      pr-prefix: "factually-settled-boxer-ci-pr-"
  create-pr-environment:
    needs: [call-metadata-workflow]
    runs-on: ubuntu-latest
    environment: gh-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}
      - name: Set Env Vars
        id: set-env-vars
        run: |
          echo "stack-name=${{ needs.call-metadata-workflow.outputs.pr-env }}" >> $GITHUB_ENV
          echo "bucket-name=${{ needs.call-metadata-workflow.outputs.pr-env }}" >> $GITHUB_ENV
      - name: Create PR Environment
        id: create-pr-env
        working-directory: ./ci
        run: |
          echo "creating new environment for PR #${{ github.event.number }}"
          aws cloudformation create-stack \
                    --template-body file://s3-website.yml \
                    --stack-name "${{ env.stack-name }}"  \
                    --parameters  ParameterKey=BucketName,ParameterValue="${{ env.bucket-name }}" \
                    --on-failure DO_NOTHING \
                    --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation wait stack-create-complete --stack-name "${{ env.stack-name }}"
          aws s3 cp --sse AES256 --acl public-read index.html "s3://${{ env.bucket-name }}/"
          aws s3 cp --sse AES256 --acl public-read error.html "s3://${{ env.bucket-name }}/error/index.html"
      - name: Comment on PR with Environment URL
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          export URL="http://${{ env.bucket-name }}.s3-website.us-east-1.amazonaws.com"
          export MESSAGE="please review changes at ${URL}"
          gh pr comment ${{ github.event.number }} --body "${MESSAGE}"
          echo "::notice title=Created PR Environment::environment url: $URL"
